function vtkwrite_example( mesh, feeders, input_file )
%% FILE MANAGEMENT
[ path, base_name, ~ ] = fileparts( input_file );
%% WRITE EDT
outfile = fullfile( path, sprintf( '%s_edt.vtk', base_name ) );
vtkwrite( ...
    outfile, ...
    'structured_points', ...
    'edt', feeders.edt, ...
    'origin', mesh.origin( 1 ), mesh.origin( 2 ), mesh.origin( 3 ), ...
    'spacing', mesh.scale, mesh.scale, mesh.scale ...
    );
%% WRITE SEGMENTATION
outfile = fullfile( path, sprintf( '%s_segments.vtk', base_name ) );
vtkwrite( ...
    outfile, ...
    'structured_points', ...
    'segments', feeders.segments, ...
    'origin', mesh.origin( 1 ), mesh.origin( 2 ), mesh.origin( 3 ), ...
    'spacing', mesh.scale, mesh.scale, mesh.scale ...
    );