function writetable_example( feeders, input_file )
%% FILE MANAGEMENT
[ path, base_name, ~ ] = fileparts( input_file );

%% TABLE SETUP
variable_names = { ...
    'number', ...
    'x', 'y', 'z', ...
    'radius', ...
    'height', ...
    'volume' ...
    };
feeder_table = table( ...
    ( 1 : feeders.count ).', ...
    feeders.position( :, 1 ), ...
    feeders.position( :, 2 ), ...
    feeders.position( :, 3 ), ...
    feeders.radius, ...
    feeders.height, ...
    feeders.volume, ...
    'variablenames', variable_names ...
    );

%% WRITE
outfile = fullfile( path, sprintf( '%s_feeders.csv', base_name ) );
writetable( feeder_table, outfile );

end

